### PR TITLE
singleton markdown added

### PR DESCRIPTION
**Pull request by imshaaz21**
This PR contains Singleton Design pattern in Java.

### CODE REVIEW

**Review by Abishethvarman — APPROVED** [review]
Seems good

**Comment by Thevapriyan07** [comment]
> _ No description provided. _


> _ No description provided. _

Please provide a description

**Review by Thevapriyan07 — CHANGES_REQUESTED** [review]
Give a description for the PR

**Comment by imshaaz21** [comment]
@Thevapriyan07 sure

**Review by Thevapriyan07 — COMMENTED** [review]
r

**Review by Abishethvarman — COMMENTED** [review]
Approved

**Pull request merged**
